apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/nginx-data
